const data = [
  {
    id: 1,
    day: "Day 1",
    date: "28th Oct 2024",
    title: "Fireside chat with Abhishek Kar: Confessions of a Stock",
    speaker: "Abhishek Kar",
    time: "9:15 PM, IST",
    venue: "Auditorium",
    link:"/",
    linkText:"Know More"
  },
  {
    id: 19,
    day: "Day 2",
    date: "29th Oct 2024",
    title: "Cultivating Growth: Financial strategies for budding startups",
    speaker: "Sri Harsha Vandakattu, VP - Finance, Sid's Farm",
    time: "3:30 PM - 4:00 PM, IST",
    venue: "Auditorium",
    link:"/",
    linkText:"Know More"
  },
  {
    id: 21,
    day: "Day 2",
    date: "29th Oct 2024",
    title: "Cultivating Growth: Financial strategies for budding startups",
    speaker: "Sri Harsha Vandakattu, VP - Finance, Sid's Farm",
    time: "3:30 PM - 4:00 PM, IST",
    venue: "Auditorium",
    link:"/",
    linkText:"Know More"
  },
  {
    id: 2,
    day: "Day 2",
    date: "29th Oct 2024",
    title: "Cultivating Growth: Financial strategies for budding startups",
    speaker: "Sri Harsha Vandakattu, VP - Finance, Sid's Farm",
    time: "3:30 PM - 4:00 PM, IST",
    venue: "Auditorium",
    link:"/",
    linkText:"Know More"
  },
  {
    id: 3,
    day: "Day 3",
    date: "30th Oct 2024",
    title: "Fireside chat with Abhishek Kar: Confessions of a Stock",
    speaker: "Abhishek Kar",
    time: "9:15 PM, IST",
    venue: "Auditorium",
    link:"/",
    linkText:"Know More"
  },
  {
    id: 4,
    day: "Day 4",
    date: "31st Oct 2024",
    title: "Fireside chat with Abhishek Kar: Confessions of a Stock",
    speaker: "Abhishek Kar",
    time: "9:15 PM, IST",
    venue: "Auditorium",
    link:"/",
    linkText:"Know More"
  },
  {
    id: 5,
    day: "Day 5",
    date: "1st Nov 2024",
    title: "Fireside chat with Abhishek Kar: Confessions of a Stock",
    speaker: "Abhishek Kar",
    time: "9:15 PM, IST",
    venue: "Auditorium",
    link:"/",
    linkText:"Know More"
  },
  {
    id: 6,
    day: "Day 6",
    date: "2nd Nov 2024",
    title: "Fireside chat with Abhishek Kar: Confessions of a Stock",
    speaker: "Abhishek Kar",
    time: "9:15 PM, IST",
    venue: "Auditorium",
    link:"/",
    linkText:"Know More"
  },
  {
    id: 7,
    day: "Day 7",
    date: "3rd Nov 2024",
    title: "Fireside chat with Abhishek Kar: Confessions of a Stock",
    speaker: "Abhishek Kar",
    time: "9:15 PM, IST",
    venue: "Auditorium",
    link:"/",
    linkText:"Know More"
  },
  {
    id: 8,
    day: "Day 1",
    date: "4th Nov 2024",
    title: "Fireside chat with Abhishek Kar: Confessions of a Stock",
    speaker: "Abhishek Kar",
    time: "9:15 PM, IST",
    venue: "Auditorium",
    link:"/",
    linkText:"Know More"
  },
  {
    id: 9,
    day: "Day 2",
    date: "5th Nov 2024",
    title: "Cultivating Growth: Financial strategies for budding startups",
    speaker: "Sri Harsha Vandakattu, VP - Finance, Sid's Farm",
    time: "3:30 PM - 4:00 PM, IST",
    venue: "Auditorium",
    link:"/",
    linkText:"Know More"
  },
  {
    id: 10,
    day: "Day 3",
    date: "6th Nov 2024",
    title: "Fireside chat with Abhishek Kar: Confessions of a Stock",
    speaker: "Abhishek Kar",
    time: "9:15 PM, IST",
    venue: "Auditorium",
    link:"/",
    linkText:"Know More"
  },
  {
    id: 11,
    day: "Day 4",
    date: "7th Nov 2024",
    title: "Fireside chat with Abhishek Kar: Confessions of a Stock",
    speaker: "Abhishek Kar",
    time: "9:15 PM, IST",
    venue: "Auditorium",
    link:"/",
    linkText:"Know More"
  },
  {
    id: 12,
    day: "Day 5",
    date: "8th Nov 2024",
    title: "Fireside chat with Abhishek Kar: Confessions of a Stock",
    speaker: "Abhishek Kar",
    time: "9:15 PM, IST",
    venue: "Auditorium",
    link:"/",
    linkText:"Know More"
  },
  {
    id: 13,
    day: "Day 6",
    date: "9 Nov 2024",
    title: "Fireside chat with Abhishek Kar: Confessions of a Stock",
    speaker: "Abhishek Kar",
    time: "9:15 PM, IST",
    venue: "Auditorium",
    link:"/",
    linkText:"Know More"
  },
  {
    id: 14,
    day: "Day 7",
    date: "10 Nov 2024",
    title: "Fireside chat with Abhishek Kar: Confessions of a Stock",
    speaker: "Abhishek Kar",
    time: "9:15 PM, IST",
    venue: "Auditorium",
    link:"/",
    linkText:"Know More"
  },
  {
    id: 15,
    day: "Day 2",
    date: "11 Nov 2024",
    title: "Cultivating Growth: Financial strategies for budding startups",
    speaker: "Sri Harsha Vandakattu, VP - Finance, Sid's Farm",
    time: "3:30 PM - 4:00 PM, IST",
    venue: "Auditorium",
    link:"/",
    linkText:"Know More"
  },
  {
    id: 16,
    day: "Day 3",
    date: "14 Nov 2024",
    title: "Fireside chat with Abhishek Kar: Confessions of a Stock",
    speaker: "Abhishek Kar",
    time: "9:15 PM, IST",
    venue: "Auditorium",
    link:"/",
    linkText:"Know More"
  },
  {
    id: 17,
    day: "Day 4",
    date: "18 Nov 2024",
    title: "Fireside chat with Abhishek Kar: Confessions of a Stock",
    speaker: "Abhishek Kar",
    time: "9:15 PM, IST",
    venue: "Auditorium",
    link:"/",
    linkText:"Know More"
  },
  {
    id: 18,
    day: "Day 5",
    date: "19 Nov 2024",
    title: "Fireside chat with Abhishek Kar: Confessions of a Stock",
    speaker: "Abhishek Kar",
    time: "9:15 PM, IST",
    venue: "Auditorium",
    link:"/",
    linkText:"Know More"
  },
  {
    id: 19,
    day: "Day 6",
    date: "24 Nov 2024",
    title: "Fireside chat with Abhishek Kar: Confessions of a Stock",
    speaker: "Abhishek Kar",
    time: "9:15 PM, IST",
    venue: "Auditorium",
    link:"/",
    linkText:"Know More"
  },
  {
    id: 20,
    day: "Day 7",
    date: "25 Nov 2024",
    title: "Fireside chat with Abhishek Kar: Confessions of a Stock",
    speaker: "Abhishek Kar",
    time: "9:15 PM, IST",
    venue: "Auditorium",
    link:"/",
    linkText:"Know More"
  },
];

export default data;
